version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
    - appveyor
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{appveyor_build_version}'
  package_version: '{appveyor_build_version}'
  assembly_version: '{appveyor_build_version}'
  file_version: '{appveyor_build_version}'
  informational_version: '{appveyor_build_version}'
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release --no-build /p:TargetFramework=netstandard2.0 ./StatsDHelper/StatsDHelper.csproj
test_script:
  - cmd: dotnet test -c Release --no-build StatsDHelper.Tests/StatsDHelper.Tests.csproj
deploy: off
#  - provider: NuGet
#    api_key: 
#      secure: IuyOJ77CDIcynzTfgeo12I2CFVaBX1mP7uidU5L8MVbF3wv0C3x+c+jy0If0+sfB
#    skip_symbols: true
#    artifact: 