version: '1.1.{build}'
image: Visual Studio 2017
branches:
  only:
    - appveyor
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release --no-build /p:TargetFramework=netstandard2.0 ./StatsDHelper/StatsDHelper.csproj
artifacts:
  - path: ./StatsDHelper/bin/Release/*.nupkg
test_script:
  - cmd: dotnet test -c Release --no-build StatsDHelper.Tests/StatsDHelper.Tests.csproj
deploy:
  - provider: NuGet
    api_key: 
      secure: mBikhs6X6BMSi9aB5JJf0udJTOzcnc2XAk/Qsg3ah6ysqp2uOHTJGNqgI6YxiFW3
    skip_symbols: true